src/11_packer/01_rg.tf, src/11_packer/20_dns_forwarder.tf, src/11_packer/21_azure_devops_agent.tf, src/11_packer/README.md
=> feat: PAYMCLOUD-234 packer setup

src/10_networking/env/itn-dev/backend.tfvars, src/10_networking/env/itn-prod/backend.tfvars, src/10_networking/env/itn-uat/backend.tfvars, src/11_packer/env/itn-dev/backend.tfvars, src/11_packer/env/itn-prod/backend.tfvars, src/11_packer/env/itn-uat/backend.tfvars, src/20_security/env/itn-dev/backend.tfvars, src/20_security/env/itn-prod/backend.tfvars, src/20_security/env/itn-uat/backend.tfvars, src/30_core/env/itn-dev/backend.tfvars, src/30_core/env/itn-prod/backend.tfvars, src/30_core/env/itn-uat/backend.tfvars, src/31_aks/env/itn-dev/backend.tfvars, src/31_aks/env/itn-prod/backend.tfvars, src/31_aks/env/itn-uat/backend.tfvars, src/41_platform/env/itn-dev/backend.tfvars, src/41_platform/env/itn-prod/backend.tfvars, src/41_platform/env/itn-uat/backend.tfvars, src/42_monitoring/env/itn-dev/backend.tfvars, src/42_monitoring/env/itn-prod/backend.tfvars, src/42_monitoring/env/itn-uat/backend.tfvars
=> feat: changed tf state name to be more clear

src/10_networking/10_vnet.tf, src/10_networking/99_variables.tf, src/10_networking/README.md, src/10_networking/env/itn-dev/terraform.tfvars, src/10_networking/env/itn-prod/terraform.tfvars, src/10_networking/env/itn-uat/terraform.tfvars
- data vnet
- computer vnet
- security vnet
Added all the vnets required
---
=> feat: Network VNETS setups

src/domains/idpay-common/.terraform.lock.hcl, src/domains/idpay-common/00_data.tf, src/domains/idpay-common/01_network.tf, src/domains/idpay-common/04_eventhub.tf, src/domains/idpay-common/99_main.tf, src/domains/idpay-common/99_variables.tf, src/domains/idpay-common/README.md, src/domains/idpay-common/env/itn-dev/terraform.tfvars, src/domains/idpay-common/env/itn-prod/terraform.tfvars, src/domains/idpay-common/env/itn-uat/terraform.tfvars, src/domains/idpay_security/99_main.tf, src/domains/idpay_security/README.md
Added Eventhub into idpay common
---
=> feat: IDP-2686 idpay common: eventhub

src/40_platform/synthetic_endpoints/monitoring_configuration.json.tpl
Introduced health monitoring configurations for various services across MIL, IDPAY, and RTD environments. Each configuration includes endpoint URLs and expected response codes.
This change establishes structured health monitoring for critical services, ensuring quick identification and resolution of service disruptions.
No additional information
=> feat: [PAYMCLOUD-311] Add service health monitoring configurations

src/70_domains/idpay_common/04_eventhub.tf, src/70_domains/idpay_common/README.md
Idpay need 2 evh because use a huge amount of partitions
---
=> feat: IDP-2712 setup eventhub castore and polluce

src/70_domains/idpay_common/00_data.tf, src/70_domains/idpay_common/01_network.tf, src/70_domains/idpay_common/06_service_bus.tf, src/70_domains/idpay_common/99_variables.tf, src/70_domains/idpay_common/README.md, src/70_domains/idpay_common/env/itn-dev/terraform.tfvars, src/70_domains/idpay_common/env/itn-prod/terraform.tfvars, src/70_domains/idpay_common/env/itn-uat/terraform.tfvars
=> feat: IDP-2689 service bus for idpay

src/70_domains/idpay_common/20_cdn.tf, src/70_domains/idpay_common/cdn/openid-configuration.json.tpl, src/70_domains/idpay_security/10_certificates.tf, src/70_domains/idpay_security/20_keys.tf, src/70_domains/idpay_security/README.md
=> feat: IDP-2722 added keys and certificates for apim apis

src/70_domains/idpay_security/00_data.tf, src/70_domains/idpay_security/01_domain_kvs.tf, src/70_domains/idpay_security/99_locals.tf, src/70_domains/idpay_security/README.md, src/70_domains/idpay_security/sops.sh, src/70_domains/idpay_security/terraform.sh
Without this policy, terraform cannot create named value
---
=> fix(idpay): Added kv policy for apim managed identity

src/10_networking/env/itn-prod/terraform.tfvars, src/11_packer/env/itn-prod/terraform.tfvars
=> feat: RTD-2611 added new forward dns image in PROD

src/10_networking/00_data.tf, src/10_networking/README.md, src/10_networking/env/itn-dev/terraform.tfvars, src/10_networking/env/itn-prod/terraform.tfvars, src/10_networking/env/itn-uat/terraform.tfvars, src/11_packer/01_rg.tf, src/11_packer/20_dns_forwarder.tf, src/11_packer/21_azure_devops_agent.tf, src/11_packer/99_main.tf, src/11_packer/README.md, src/11_packer/env/itn-dev/terraform.tfvars, src/11_packer/env/itn-prod/terraform.tfvars, src/11_packer/env/itn-uat/terraform.tfvars, src/30_core/00_data.tf, src/30_core/06_azure_devops_agent.tf, src/30_core/99_locals.tf, src/30_core/README.md, src/30_core/env/itn-dev/terraform.tfvars, src/30_core/env/itn-prod/terraform.tfvars, src/30_core/env/itn-uat/terraform.tfvars
- updated all images with kubectl 1.31
- now the images are created in the rg where are needed and not more into packer rg
- updated vmss for azdo agents
---
=> feat: RTD-2621 azdo agent now in Italy network hub

src/10_networking/10_vnet.tf, src/10_networking/12_peering.tf, src/10_networking/12_peering_legacy.tf, src/10_networking/README.md
- removed vnet platform
- remover peerings
Vnet platform is not used anymore
---
=> feat: Removed vnet platform and its peerings

src/70_domains/idpay_common/21_cdn_assetregister.tf, src/70_domains/idpay_common/env/itn-dev/terraform.tfvars, src/70_domains/idpay_common/env/itn-prod/terraform.tfvars, src/70_domains/idpay_common/env/itn-uat/terraform.tfvars
- Update hostname and path 
---
=> fix: update hostname and path

src/40_platform/99_locals.tf
=> feat: Added srtp default resource groups

src/70_domains/srtp_security/secrets/srtp/itn-prod/noedit_secret_enc.json
=> feat(srtp): Added github bot tokens in PROD

src/20_security_kv/secrets/core/itn-prod/noedit_secret_enc.json, src/20_security_kv/secrets/core/itn-uat/noedit_secret_enc.json
=> feat: Added missing secrets

src/70_domains/idpay_app/30_argocd_domain.tf
=> feat: Delete keycloak

src/40_platform/01_default_resource_groups.tf, src/40_platform/01_tags.tf, src/40_platform/11_monitoring.tf, src/40_platform/20_synthetic_setup.tf, src/40_platform/21_synthetic_job.tf, src/40_platform/30_grafana_managed.tf, src/40_platform/99_main.tf, src/40_platform/99_variables.tf, src/40_platform/README.md, src/40_platform/env/itn-dev/terraform.tfvars, src/40_platform/env/itn-prod/terraform.tfvars, src/40_platform/env/itn-uat/terraform.tfvars
=> feat: [IDP-2746] add monitoring and grafana@uat

src/20_security_kv/secrets/core/itn-uat/noedit_secret_enc.json
=> chore: [IDP-2746] grafana token@uat

src/70_domains/idpay_app/99_variables.tf, src/70_domains/idpay_app/README.md, src/70_domains/idpay_app/env/itn-dev/terraform.tfvars, src/70_domains/idpay_app/env/itn-prod/terraform.tfvars, src/70_domains/idpay_app/env/itn-uat/terraform.tfvars
- install idpay app on uat
- removed variables not more used
---
=> feat: IDP-2749 idpay app on UAT

src/20_security_kv/secrets/cicd/itn-prod/noedit_secret_enc.json, src/91_github/idpay/.terraform.lock.hcl, src/91_github/idpay/00_data.tf, src/91_github/idpay/01_github_environments.tf, src/91_github/idpay/02_branch_protection.tf, src/91_github/idpay/99_locals.tf, src/91_github/idpay/99_main.tf, src/91_github/idpay/99_variables.tf, src/91_github/idpay/README.md, src/91_github/idpay/env/prod/backend.ini, src/91_github/idpay/env/prod/backend.tfvars, src/91_github/idpay/env/prod/terraform.tfvars, src/91_github/idpay/terraform.sh
=> feat: Add github configuration

src/70_domains/srtp_common/00_data.tf, src/70_domains/srtp_common/01_network.tf, src/70_domains/srtp_common/README.md
=> feat(srtp): Nat GW association with CAE

src/20_security_kv/01_core_kvs.tf, src/20_security_kv/README.md
=> fix: Kv policy

src/31_aks_italy/env/itn-uat/terraform.tfvars, src/70_domains/idpay_common/env/itn-uat/terraform.tfvars
=> feat: RTD-2646 aks uat alligment with standards

src/91_github/idpay/02_branch_protection.tf, src/91_github/idpay/99_locals.tf, src/91_github/idpay/99_main.tf, src/91_github/idpay/README.md
This PR proposes to add the idpay merchant repository among the ones configured via terraform.
Plus, replaces the old branch protection with the more modern repository rulesets.
The rulesets consist of 2 rules, following the adopted git flow branching model:
- one for dev with less restrictive rules and *when supported* will be allowed to merge the PRs only with the squash method.
- one for uat and prod with the merge method only and some restrictions to the deletion of merged branch 
---
=> fix: added idpay merchant in GitHub repos

src/31_aks_italy/02_aks_node_pools.tf, src/70_domains/idpay_common/30_aks_node_pool.tf
Allow to manage migration and nodes in a better way
---
=> feat: AKS Italy added node pool blue and green

src/70_domains/idpay_app/30_argocd_domain.tf
Allow to avoid to install some application in some envs
---
=> feat(idpay): added env info into argocd applications

src/31_aks_italy/10_argocd.tf, src/31_aks_italy/99_variables.tf, src/31_aks_italy/argocd/argocd_helm_setup_values.yaml, src/31_aks_italy/env/itn-dev/terraform.tfvars, src/31_aks_italy/env/itn-prod/terraform.tfvars, src/31_aks_italy/env/itn-uat/terraform.tfvars
Improve the values used by helm, to allow to setup values and configurations for prod
---
=> feat: RTD-2649 ArgoCD ready for PROD

src/70_domains/idpay_common/00_data.tf, src/70_domains/idpay_common/08_storage_audit_log.tf, src/70_domains/idpay_common/20_cdn_selfcare.tf, src/70_domains/idpay_common/21_cdn_assetregister.tf, src/70_domains/idpay_common/21_cdn_bonus_elettrodomestici.tf, src/70_domains/idpay_common/21_cdn_portal_merchants_operator.tf, src/70_domains/idpay_common/21_cdn_welfare.tf, src/70_domains/idpay_common/31_aks_audit_data_collections.tf, src/70_domains/idpay_common/99_locals.tf
=> feat(idpay): IDP-2720 Added audit logs for aks

src/70_domains/idpay_common/.terraform.lock.hcl, src/70_domains/idpay_common/03_cosmos_mongodb_configuration.tf
Add index for products collection
Need to search and order for specific fields
---
=> feat: RDB-64 produt file index update

.github/workflows/static_analysis_pr.yml, src/31_aks_italy/argocd/argocd_helm_setup_values.yaml
- Updated topology spread constraints in the ArgoCD Helm configuration.
- Enabled error-level logging for better troubleshooting and diagnostics.
These changes aim to improve the scalability and resiliency of the ArgoCD deployment by refining topology spread constraints. Additionally, enabling error-level logging enhances the ability to identify and resolve issues effectively.
No additional notes.
=> fix: [IDP-2780] Adjust ArgoCD Helm setup: update constraints and logging level

src/70_domains/idpay_common/00_data.tf, src/70_domains/idpay_common/20_monitor.tf
- Added configuration for APIM data source.
- Integrated logger configuration for tracking and debugging.
This change is required to set up an APIM as a data source and enhance logging capabilities for better monitoring and debugging of the system.
N/A
---
N/A
=> feat: [IDP-2783] Add APIM data source and logger configuration

src/70_domains/idpay_app/04_eventhub_config_kafka_connectors.tf, src/70_domains/idpay_app/30_argocd_domain.tf, src/70_domains/idpay_app/README.md, src/70_domains/idpay_app/env/itn-prod/terraform.tfvars
- Commented out unused resources 
- Updated ingress domain hostname for ITN production environment
These changes clean up unused resources and ensure that the ingress domain hostname aligns with the latest configuration for the ITN production environment.
N/A
---
=> feat: [IDP-2763] Update ingress domain hostname for ITN production

src/70_domains/mcshared-common/.terraform.lock.hcl, src/70_domains/mcshared-common/06_container_app.tf, src/70_domains/mcshared-common/99_main.tf, src/70_domains/mcshared-common/README.md, src/70_domains/srtp_common/30_container_app.tf, src/70_domains/srtp_common/README.md
=> feat: Paymcloud 458 aca logs to azuremonitor

src/70_domains/idpay_app/04_eventhub_config_kafka_connectors.tf, src/70_domains/idpay_app/README.md
- Enabled deployment for `transaction_in_progress_connector`.
- Updated README with details regarding `null` provider configuration.
This change allows the deployment of the `transaction_in_progress_connector` as needed, improving functionality. The README update provides clear guidance on using the `null` provider.
N/A
--- 
N/A
=> feat: [IDP-2763] Enable `transaction_in_progress_connector` and update README  

src/70_domains/idpay_common/03_cosmos_mongodb_configuration.tf
Add index for collections point of sales and transaction in progress
allow research and order for some fileds in trx in progress and point of sales collections
---
=> feat: EBE-68 EBE-69 add index for transaction_in_progress and point_of_sales

src/20_security_kv/secrets/cicd/itn-dev/noedit_secret_enc.json, src/20_security_kv/secrets/cicd/itn-prod/noedit_secret_enc.json, src/20_security_kv/secrets/cicd/itn-uat/noedit_secret_enc.json, src/20_security_kv/secrets/core/itn-uat/noedit_secret_enc.json, src/40_platform/00_data.tf, src/40_platform/10_network.tf, src/40_platform/40_github_cae.tf, src/40_platform/99_main.tf, src/40_platform/README.md, src/70_domains/mcshared-common/06_container_app.tf, src/70_domains/srtp_app/.terraform.lock.hcl, src/70_domains/srtp_app/07_gh_runner.tf, src/70_domains/srtp_app/99_locals.tf, src/70_domains/srtp_app/99_main.tf, src/70_domains/srtp_app/README.md, src/70_domains/srtp_common/.terraform.lock.hcl, src/70_domains/srtp_common/00_data.tf, src/70_domains/srtp_common/40_namespace_+_workload_identity.tf, src/70_domains/srtp_common/99_locals.tf, src/70_domains/srtp_common/99_main.tf, src/70_domains/srtp_common/README.md, src/91_github/srtp/00_data.tf, src/91_github/srtp/02_environment.tf, src/91_github/srtp/03_environment_variables.tf, src/91_github/srtp/99_locals.tf, src/91_github/srtp/README.md
=> feat: [Srtp-765] Add GitHub runner & SRTP namespace

src/70_domains/idpay_common/21_cdn_bonus_elettrodomestici.tf
Add api-mcshared in host allowed
---
=> fix: Cdn bonus elettrodom update

src/70_domains/idpay_common/21_cdn_bonus_elettrodomestici.tf
=> fix: Rewrite bonus - utente

src/70_domains/idpay_common/.terraform.lock.hcl, src/70_domains/idpay_common/03_cosmos_mongodb_configuration.tf
=> fix: rdb product index update

src/70_domains/idpay_common/10_keycloak.tf
Add dateOfBirth attribute to keyacloack access token and id token
Need to check the date of birth of a users
---
=> feat: UPBE-137 add dateOfBirth attrbuto to keycloack token

src/31_aks_italy/20_rbac.tf, src/70_domains/idpay_common/21_cdn_assetregister.tf
=> fix: [IDPAY] IAC

.devops/grafanaconf-deploy-pipelines.yml, .devops/idpay-deploy-pipelines.yml, src/91_github/idpay/.terraform.lock.hcl, src/91_github/idpay/README.md
=> fix: IAC devops

src/70_domains/idpay_app/30_argocd_domain.tf
=> chore: idpay ranker added

src/30_core/06_azure_devops_agent.tf, src/30_core/README.md
=> feat: [RTD-2653] add perf agent pool

src/70_domains/idpay_security/secrets/idpay/itn-prod/noedit_secret_enc.json
This PR proposes to add the merchant selfcare api key in prod. The value is a **placeholder** waiting for the correct key.
---
=> fix: add missing merchant selfcare api-key in prod

src/70_domains/idpay_security/secrets/idpay/itn-prod/noedit_secret_enc.json
This PR proposes to update the secret values of selfcare's api keys with the correct ones.
---
=> fix: [LTBE-17] add selfcare api key in prod

src/0_entra/10_argocd_entra.tf, src/0_entra/99_main.tf, src/0_entra/README.md, src/40_platform/50_argocd.tf, src/40_platform/99_main.tf, src/40_platform/README.md, src/70_domains/idpay_common/21_cdn_assetregister.tf, src/70_domains/idpay_common/21_cdn_bonus_elettrodomestici.tf, src/70_domains/idpay_common/21_cdn_selfcare.tf, src/70_domains/idpay_common/21_cdn_welfare.tf, src/70_domains/idpay_common/99_main.tf
Use the pinned module version for argocd and front door
---
=> fix: Update source modules for argocd and cdn front door

src/70_domains/idpay_app/configs/workbooks/OPEXWorkbook.json.tpl
This PR proposes to update the workbook EIE section
---
=> fix: Eie work book update

src/40_platform/50_argocd.tf, src/40_platform/99_main.tf, src/40_platform/README.md, src/70_domains/idpay_common/08_storage_audit_log.tf, src/70_domains/idpay_common/21_cdn_assetregister.tf, src/70_domains/idpay_common/21_cdn_bonus_elettrodomestici.tf, src/70_domains/idpay_common/21_cdn_selfcare.tf, src/70_domains/idpay_common/21_cdn_welfare.tf, src/70_domains/idpay_common/99_main.tf, src/70_domains/idpay_common/env/itn-uat/terraform.tfvars
=> fix: Storage & law daily

src/70_domains/idpay_app/30_argocd_domain.tf
=> chore: delete idpay mock from prod

src/40_platform/env/itn-prod/terraform.tfvars, src/40_platform/env/itn-uat/terraform.tfvars
=> fix: influxdb Allign variables in uat and prod

src/70_domains/idpay_app/08_k8s_configmaps.tf
=> feat: UPBE-190-BE]-Added idpay-payment-host

.devops/grafanaconf-code-review-pipelines.yml, .devops/grafanaconf-deploy-pipelines.yml
=> fix: Grafana IAC

src/70_domains/idpay_app/configs/kafka-connectors/transaction_in_progress_connector.json
=> feat: EBE-257 add captured and expired state
